import { useId, useMemo, useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import {
  appendFrontContinuation,
  type AppendFrontContinuationResult,
} from '@/application/fleet-setup/append-front-continuation'
import { appendNewBaseFront, type AppendNewBaseFrontResult } from '@/application/fleet-setup/append-new-base-front'
import { availableAddedTruckIds, truckOptionsForHauler } from '@/application/fleet-setup/effective-fleet-preview'
import type { ActivatedPile } from '@/application/pile-master/activate-new-pile'
import type { NewPileDraft } from '@/application/pile-master/create-pile-area-from-draft'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { SearchableCombobox, type SearchableComboboxOption } from '@/components/shared/SearchableCombobox'
import type { DomainError, Result } from '@/domain/common/result'
import { resolveEffectiveFleetAgainstMaster } from '@/domain/fleet/fleet-resolution'
import type { FleetSetup } from '@/domain/fleet/fleet-setup'
import { deriveFrontLineage } from '@/domain/fleet/front-lineage'
import type { MasterData } from '@/domain/master/master-data'
import { createPile, type Pile } from '@/domain/pile/pile'
import type { Shift } from '@/domain/shift/shift'
import { EffectiveFleetPreview } from '@/features/fleet-setup/effective-fleet-preview'
import { SelectedTrucks, TruckAction } from '@/features/fleet-setup/truck-action-controls'
import { fleetActiveErrorTranslationKey } from '@/features/fleet/error-messages'
import { NewPileForm } from '@/features/pile-master/new-pile-form'

export interface FrontContinuationEditorProps {
  readonly shift: Shift
  readonly masterData: MasterData
  readonly fleetSetup: FleetSetup
  readonly workspacePiles: readonly Pile[]
  /** Pre-generated by the caller (mirrors `FleetSetupPage`'s `generateFleetId`), so a retry after a save keeps a stable id for this one editing session. */
  readonly fleetId: string
  /** Post-init New Pile Master creation (`activateNewPile`) — omit to hide the "+ Add New Pile" destination fallback. */
  readonly createNewPile?: (draft: NewPileDraft) => Promise<Result<ActivatedPile, DomainError>>
  /** Called immediately after a new Pile Master is created via `createNewPile`, so this editor's own `masterData`/`workspacePiles` stay in sync (mirrors `FrontEditor.onMasterDataUpdated`). */
  onPileActivated?: (activated: ActivatedPile) => void
  onSave: (result: AppendFrontContinuationResult | AppendNewBaseFrontResult, activatePile?: Pile) => void
  onCancel: () => void
}

/**
 * "+ Tambah Front" editor during an active shift (Phase 18 §2). Supports
 * TWO modes off one Fleet Reference selector, mirroring the pre-shift
 * `FrontEditor`'s BASE/DERIVED split:
 *
 *  - CONTINUATION (Fleet Reference = an ACTIVE Front): Front No is
 *    always auto-derived, Hauler/Destination/effective trucks are
 *    inherited from the reference (Destination stays editable), and the
 *    reference Front becomes HISTORICAL once saved (`appendFrontContinuation`).
 *  - BASE (Fleet Reference = "Tidak Ada"): a compact version of the
 *    initial Fleet Setup's BASE front — the operator picks a Hauler, a
 *    Destination (required — there is no reference to inherit one from),
 *    and Trucks from that Hauler, reusing the same BASE `FleetDefinition`
 *    model (`appendNewBaseFront`) rather than a second fleet shape. No
 *    predecessor Front is ever retired by this mode.
 *
 * Every validation and fleet-math step is delegated to
 * `appendFrontContinuation`/`appendNewBaseFront` — this component only
 * collects input, derives which mode is active from the Fleet Reference
 * selection, and renders the result.
 */
export function FrontContinuationEditor({
  shift,
  masterData,
  fleetSetup,
  workspacePiles,
  fleetId,
  createNewPile,
  onPileActivated,
  onSave,
  onCancel,
}: FrontContinuationEditorProps) {
  const { t } = useTranslation()
  const referenceSelectId = useId()
  const haulerSelectId = useId()
  const baseTruckSelectId = useId()
  const addTruckSelectId = useId()
  const removeTruckSelectId = useId()

  const lineage = useMemo(() => deriveFrontLineage(fleetSetup), [fleetSetup])
  const activeFronts = useMemo(
    () => fleetSetup.fronts.filter((front) => lineage.activeFrontIds.includes(front.frontId)),
    [fleetSetup.fronts, lineage.activeFrontIds],
  )

  const [referenceFrontId, setReferenceFrontId] = useState<string>(() => activeFronts[0]?.frontId ?? '')
  const referenceFront = fleetSetup.fronts.find((front) => front.frontId === referenceFrontId)
  const referenceFleet = fleetSetup.fleets.find((fleet) => fleet.frontId === referenceFrontId)
  // "Tidak Ada" (Fleet Reference blank) means a brand-new independent
  // BASE Front (Phase 18 §2), not "nothing chosen yet" — the default
  // state above already picks the first ACTIVE Front when one exists.
  const mode: 'CONTINUATION' | 'BASE' = referenceFrontId === '' ? 'BASE' : 'CONTINUATION'

  const [destinationPileId, setDestinationPileId] = useState<string>(() => referenceFront?.destinationPileId ?? '')
  const [destinationQuery, setDestinationQuery] = useState('')
  const [creatingDestination, setCreatingDestination] = useState(false)
  const [addedTruckIds, setAddedTruckIds] = useState<readonly string[]>([])
  const [removedTruckIds, setRemovedTruckIds] = useState<readonly string[]>([])
  const [selectedAddTruck, setSelectedAddTruck] = useState('')
  const [selectedRemoveTruck, setSelectedRemoveTruck] = useState('')
  const [haulerCode, setHaulerCode] = useState('')
  const [baseTruckIds, setBaseTruckIds] = useState<readonly string[]>([])
  const [selectedBaseTruck, setSelectedBaseTruck] = useState('')
  const [submitErrorCode, setSubmitErrorCode] = useState<string>()

  function handleReferenceChange(value: string) {
    const front = fleetSetup.fronts.find((candidate) => candidate.frontId === value)
    setReferenceFrontId(value)
    setDestinationPileId(front?.destinationPileId ?? '')
    setDestinationQuery('')
    setCreatingDestination(false)
    setAddedTruckIds([])
    setRemovedTruckIds([])
    setSelectedAddTruck('')
    setSelectedRemoveTruck('')
    setHaulerCode('')
    setBaseTruckIds([])
    setSelectedBaseTruck('')
    setSubmitErrorCode(undefined)
  }

  const inheritedTruckIds = useMemo(() => {
    if (!referenceFleet) return []
    const resolved = resolveEffectiveFleetAgainstMaster(masterData, fleetSetup, referenceFleet.fleetId)
    return resolved.ok ? resolved.value.truckIds : []
  }, [referenceFleet, masterData, fleetSetup])

  const addOptions = referenceFront
    ? availableAddedTruckIds(masterData, referenceFront.haulerCode, inheritedTruckIds, addedTruckIds, removedTruckIds)
    : []
  const removeOptions = inheritedTruckIds.filter(
    (id) => !addedTruckIds.includes(id) && !removedTruckIds.includes(id),
  )
  const baseTruckOptions = truckOptionsForHauler(masterData, haulerCode).filter((id) => !baseTruckIds.includes(id))

  const destinationCandidates: readonly SearchableComboboxOption[] = useMemo(() => {
    const normalized = destinationQuery.trim().toLowerCase()
    if (!normalized) return []
    return masterData.pileAreas
      .filter(
        (pileArea) =>
          pileArea.sectorCode === shift.sectorCode &&
          ((pileArea.pileId as string).toLowerCase().includes(normalized) ||
            (pileArea.stockpileCode as string).toLowerCase().includes(normalized)),
      )
      .map((pileArea) => ({
        value: pileArea.pileId as string,
        label: pileArea.pileId as string,
        description: `${pileArea.oreCode} · ${pileArea.stockpileCode}`,
      }))
  }, [destinationQuery, masterData.pileAreas, shift.sectorCode])

  const selectedDestination = destinationPileId
    ? masterData.pileAreas.find((pileArea) => pileArea.pileId === destinationPileId)
    : undefined

  const candidate = useMemo(
    () =>
      mode === 'CONTINUATION'
        ? appendFrontContinuation({
            fleetSetup,
            masterData,
            referenceFrontId,
            destinationPileId: destinationPileId || undefined,
            addedTruckIds,
            removedTruckIds,
            fleetId,
          })
        : appendNewBaseFront({
            fleetSetup,
            masterData,
            sectorCode: shift.sectorCode,
            haulerCode,
            destinationPileId,
            truckIds: baseTruckIds,
            fleetId,
          }),
    [
      mode,
      fleetSetup,
      masterData,
      referenceFrontId,
      destinationPileId,
      addedTruckIds,
      removedTruckIds,
      haulerCode,
      baseTruckIds,
      fleetId,
      shift.sectorCode,
    ],
  )

  function handleSubmit(event: FormEvent) {
    event.preventDefault()
    if (!candidate.ok) {
      setSubmitErrorCode(candidate.error.code)
      return
    }
    const activatePile = destinationPileId
      ? (() => {
          const pileArea = masterData.pileAreas.find((candidatePileArea) => candidatePileArea.pileId === destinationPileId)
          const alreadyActive = workspacePiles.some((pile) => pile.id === destinationPileId)
          return pileArea && !alreadyActive ? createPile(pileArea.pileId, pileArea.oreCode) : undefined
        })()
      : undefined
    onSave(candidate.value, activatePile)
  }

  const displayErrorCode = submitErrorCode ?? (!candidate.ok ? candidate.error.code : undefined)

  return (
    <Card>
      <CardHeader>
        <CardTitle>{t('fleetActive.addFront')}</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} noValidate className="flex flex-col gap-4">
          <div className="flex flex-col gap-1.5">
            <span className="text-sm font-medium">{t('fleetActive.newFront')}</span>
            <output className="min-h-11 break-all rounded-md border border-border bg-muted px-3 py-2.5">
              {candidate.ok ? candidate.value.newFront.frontId : '—'}
            </output>
          </div>

          <div className="flex flex-col gap-1.5">
            <label htmlFor={referenceSelectId} className="text-sm font-medium">
              {t('fleetSetup.referenceFleet')}
            </label>
            <select
              id={referenceSelectId}
              value={referenceFrontId}
              onChange={(event) => handleReferenceChange(event.target.value)}
              className="h-11 rounded-md border border-border bg-background px-3 text-base"
            >
              <option value="">{t('fleetSetup.noReference')}</option>
              {activeFronts.map((front) => (
                <option key={front.frontId} value={front.frontId}>
                  {front.frontId}
                </option>
              ))}
            </select>
          </div>

          {mode === 'BASE' ? (
            <div className="flex flex-col gap-1.5">
              <label htmlFor={haulerSelectId} className="text-sm font-medium">
                {t('fleetSetup.hauler')}
              </label>
              <select
                id={haulerSelectId}
                value={haulerCode}
                onChange={(event) => {
                  setHaulerCode(event.target.value)
                  setBaseTruckIds([])
                  setSelectedBaseTruck('')
                }}
                className="h-11 rounded-md border border-border bg-background px-3 text-base"
              >
                <option value="">—</option>
                {masterData.haulers.map((hauler) => (
                  <option key={hauler.code} value={hauler.code}>
                    {hauler.code}
                  </option>
                ))}
              </select>
            </div>
          ) : null}

          {creatingDestination ? (
            <NewPileForm
              initialPileId={destinationQuery.trim()}
              sectorCode={shift.sectorCode}
              masterData={masterData}
              onSubmit={(draft) => {
                if (!createNewPile) {
                  return Promise.resolve({
                    ok: false as const,
                    error: {
                      code: 'PILE_MASTER_CREATION_UNAVAILABLE',
                      message: 'New Pile Master creation is not available here',
                    },
                  })
                }
                return createNewPile(draft)
              }}
              onCreated={(activated) => {
                onPileActivated?.(activated)
                setDestinationPileId(activated.pileArea.pileId)
                setCreatingDestination(false)
                setDestinationQuery('')
              }}
              onCancel={() => setCreatingDestination(false)}
            />
          ) : (
            <SearchableCombobox
              label={t('fleetSetup.destinationPile')}
              query={destinationQuery}
              onQueryChange={setDestinationQuery}
              options={destinationCandidates}
              onSelect={(option) => {
                setDestinationPileId(option.value)
                setDestinationQuery('')
              }}
              selectedLabel={
                destinationPileId
                  ? `${destinationPileId}${selectedDestination ? ` (${selectedDestination.oreCode} · ${selectedDestination.stockpileCode})` : ''}`
                  : undefined
              }
              clearLabel={t('fleetSetup.change')}
              onClearSelection={() => setDestinationPileId('')}
              placeholder={t('fleetSetup.destinationPilePlaceholder')}
              noResultsContent={
                createNewPile && destinationQuery.trim() ? (
                  <Button type="button" variant="secondary" onClick={() => setCreatingDestination(true)}>
                    {t('pileMaster.addNewPileNamed', { pileId: destinationQuery.trim() })}
                  </Button>
                ) : (
                  <p className="text-sm text-muted-foreground">{t('fleetSetup.destinationPileNotFound')}</p>
                )
              }
            />
          )}

          {mode === 'BASE' ? (
            <section className="flex flex-col gap-3 rounded-lg border border-border p-3">
              <h4 className="font-semibold">{t('fleetSetup.allowedTrucks')}</h4>
              <TruckAction
                id={baseTruckSelectId}
                label={t('fleetSetup.addTruck')}
                actionLabel={t('fleetSetup.addTruck')}
                options={baseTruckOptions}
                value={selectedBaseTruck}
                onValueChange={setSelectedBaseTruck}
                onAction={(truckId) => {
                  if (!baseTruckOptions.includes(truckId)) return
                  setBaseTruckIds((current) => [...current, truckId])
                  setSelectedBaseTruck('')
                }}
              />
              <SelectedTrucks
                truckIds={baseTruckIds}
                actionLabel={(id) => t('fleetSetup.removeTruckNamed', { truckId: id })}
                onRemove={(id) => setBaseTruckIds((current) => current.filter((truckId) => truckId !== id))}
              />
            </section>
          ) : (
            <>
              <EffectiveFleetPreview truckIds={inheritedTruckIds} titleKey="fleetSetup.inheritedTrucks" />

              <section className="flex flex-col gap-3 rounded-lg border border-emerald-300 bg-emerald-50 p-3">
                <h4 className="font-semibold text-emerald-950">{t('fleetSetup.addedTrucks')}</h4>
                <TruckAction
                  id={addTruckSelectId}
                  label={t('fleetSetup.addTruck')}
                  actionLabel={t('fleetSetup.addTruck')}
                  options={addOptions}
                  value={selectedAddTruck}
                  onValueChange={setSelectedAddTruck}
                  onAction={(truckId) => {
                    if (!addOptions.includes(truckId)) return
                    setAddedTruckIds((current) => [...current, truckId])
                    setSelectedAddTruck('')
                  }}
                />
                <SelectedTrucks
                  truckIds={addedTruckIds}
                  actionLabel={(id) => t('fleetSetup.removeAddedTruckNamed', { truckId: id })}
                  onRemove={(id) => setAddedTruckIds((current) => current.filter((truckId) => truckId !== id))}
                />
              </section>

              <section className="flex flex-col gap-3 rounded-lg border border-amber-300 bg-amber-50 p-3">
                <h4 className="font-semibold text-amber-950">{t('fleetSetup.removedTrucks')}</h4>
                <TruckAction
                  id={removeTruckSelectId}
                  label={t('fleetSetup.removeTruck')}
                  actionLabel={t('fleetSetup.removeTruck')}
                  options={removeOptions}
                  value={selectedRemoveTruck}
                  onValueChange={setSelectedRemoveTruck}
                  onAction={(truckId) => {
                    const selectedTruckId = removeOptions.find((candidate) => candidate === truckId)
                    if (!selectedTruckId) return
                    setRemovedTruckIds((current) => [...current, selectedTruckId])
                    setSelectedRemoveTruck('')
                  }}
                />
                <SelectedTrucks
                  truckIds={removedTruckIds}
                  actionLabel={(id) => t('fleetSetup.restoreRemovedTruckNamed', { truckId: id })}
                  onRemove={(id) => setRemovedTruckIds((current) => current.filter((truckId) => truckId !== id))}
                />
              </section>
            </>
          )}

          <EffectiveFleetPreview
            truckIds={candidate.ok ? candidate.value.effectiveFleet.truckIds : []}
            errorKey={displayErrorCode ? fleetActiveErrorTranslationKey(displayErrorCode) : undefined}
          />

          <div className="grid grid-cols-2 gap-2">
            <Button type="button" variant="secondary" onClick={onCancel}>
              {t('fleetSetup.cancel')}
            </Button>
            <Button type="submit">{t('fleetSetup.saveFront')}</Button>
          </div>
        </form>
      </CardContent>
    </Card>
  )
}
